# Generated by Django 3.0.7 on 2020-07-23 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='height',
        ),
    ]
