# Generated by Django 3.0.7 on 2020-07-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_shoe_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='feature',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='detail',
            name='sub_detail',
            field=models.CharField(max_length=500),
        ),
    ]
