# Generated by Django 3.0.7 on 2020-07-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200723_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='subimage',
            name='is_hover',
            field=models.BooleanField(default=False),
        ),
    ]
