# Generated by Django 3.0.7 on 2020-07-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagram',
            name='image',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='instagram',
            name='user_profile_image',
            field=models.URLField(max_length=300),
        ),
    ]
